### ISSUE TITLE
version

### ISSUE THREAD

**Issue by VivianDem** [IAEA-NSDDNetwork/FMTCHK-#1]
In the comments section the last version of the code is 10.5d, while in the display header in the output file it is given as 10.4d. This creates confusion especially since we are asked to display the version of the code on the IAEA ENSDF webpage. Can you fix this?

Also, have you tested this source code on linux and mac os?

**Comment by donniemmason** [comment]
The version is now changed to the latest, 10.5d. The source code was tested on Windows, Linux, and Mac OS with gfortran. The Makefile will build an executable for the appropriate operating system with the "make" command.
